#!/bin/sh
set -e

MSG_FILE="$1"

# Disallow bracketed types like [feat]
if grep -qE '^\[[A-Za-z]+\]' "$MSG_FILE"; then
  echo "Use 'type: subject' format. Bracketed types like [feat] are not allowed."
  exit 1
fi

exit 0
